---
# tasks file for addldap
# This task writes an auth.conf.xml file to the galaxy settings directory
# and installs the python ldap module in the container's virtual environment.
- name: Show ldap variables
  debug:
    var: ldap
    verbosity: 1

- name: register whether the container is running
  command: "docker inspect -f {{inspect}} {{docker_container_name}}"
  vars:
    inspect: !unsafe '{{.State.Running}}'
  register: docker_running

- name: Show docker inspection results
  debug:
    var: docker_running
    verbosity: 1

- name: Make sure the docker container is started
  docker_container:
    name: "{{docker_container_name}}"
    state: started
  when: not docker_running.stdout | bool

- name: Register whether config folder is already created
  stat:
    path: "{{docker_export_location}}/galaxy-central/config"
  register: default_config_folder
  until: default_config_folder.stat.exists
  retries: 10
  delay: 10

- name: Create auth_conf.xml file in config folder
  template:
    dest: "{{docker_export_location}}/galaxy-central/config/auth_conf.xml"
    force: yes
    src: auth_conf.xml.j2
    owner: "{{container_galaxy_user}}"
    group: "{{container_galaxy_user}}"
    mode: 0700

- name:  Create script to include python-ldap and restart the container
  template:
    dest: "{{docker_export_location}}/install_python_ldap.sh"
    mode: 700
    src: install_python_ldap.sh.j2

- name: install python_ldap in docker container
  command: "docker exec {{name}} {{command}}"
  vars:
    name: "{{docker_container_name}}"
    command: /export/install_python_ldap.sh
  register: ldap_python_install

- name: show installationresults
  debug:
    var: ldap_python_install.stdout
