---
galaxy_docker_tool_list_dir: "{{playbook_dir}}/files/{{ inventory_hostname }}/tools/"
galaxy_docker_backup_db_dir: "{{ inventory_hostname }}/backup_db"
galaxy_docker_import_db_dir: "{{ inventory_hostname }}/database_import"
galaxy_docker_ssh_dir: "{{playbook_dir}}/files/{{ inventory_hostname }}/ssh"
galaxy_docker_welcome_dir: "{{playbook_dir}}/files/{{ inventory_hostname }}/welcome/"
galaxy_docker_genomes_dir: "{{playbook_dir}}/files/{{inventory_hostname}}/genomes/"
galaxy_docker_dbkeys_list_dir: "{{playbook_dir}}/files/{{inventory_hostname}}/dbkeys/"
galaxy_docker_custom_image_dir: "files/{{inventory_hostname}}/docker_custom_image/"
galaxy_docker_extract_database_dir: "files/{{inventory_hostname}}/database_extract/"
