---
#Required settings
# Please uncomment and specify these values yourself

# galaxy_admin_user: "example@example.nl"
# galaxy_master_api_key: "8374uhiuy893749872302" #replace with your own key!!
# galaxy_brand: "Instance of Galaxy"
# galaxy_report_user: admin
# galaxy_report_password: admin

#optional settings
galaxy_docker_optional_environment_settings:
  GALAXY_CONFIG_CONDA_AUTO_INSTALL: True
  GALAXY_CONFIG_CONDA_AUTO_INIT: True
  GALAXY_CONFIG_USE_CACHED_DEPENDENCY_MANAGER: True
  NONUSE: proftp
#  GALAXY_CONFIG_AUTH_CONFIG_FILE: "config/auth_conf.xml"
