---
galaxy_docker_upgrade_overwrite_config_files: False

galaxy_docker_upgrade_test_settings:
  galaxy_docker_docker_image: "bgruening/galaxy-stable:18.05"
  galaxy_docker_container_name: test_upgrade_galaxy
  galaxy_docker_export_location: "/data/galaxy/test_upgrade_galaxy/galaxy_storage"
  galaxy_docker_web_port: 8888
  galaxy_docker_web_port_public: 8880
  galaxy_brand: "Test upgrade of Galaxy to 18.05"
