---
# Copyright 2017 Sequencing Analysis Support Core - Leiden University Medical Center
# Contact us at: sasc@lumc.nl
#
# This file is part of galaxy-docker-ansible.
# A dual licensing mode is applied.
# The source code within this project is freely available for non-commercial use under the GNU Affero General Public license.
# For commercial users or users who do not want to follow the AGPL, please contact us to obtain a separate license.
#
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <http://www.gnu.org/licenses/>.

# handlers file for galaxy_docker

- name: check if galaxy has started
  uri:
    url: "http://localhost:{{galaxy_web_port}}"
    return_content: yes
  register: result
  until: 'galaxy_brand in result.content'
  retries: 20
  delay: 10

- name: check if provision galaxy has started
  uri:
    url: "http://localhost:{{galaxy_docker_provision_port}}"
    return_content: yes
  register: result
  until: 'galaxy_brand in result.content'
  retries: 20
  delay: 10

- name: restart galaxy in container
  command: "docker exec {{docker_container_name}} {{command}}"
  vars:
    command: "supervisorctl restart {{supervisorctl_galaxy | default('galaxy')}}:*"
  notify: check if galaxy has started
